schema_version: 1
project: BLUE
runtime: original-game-boy-rom

sources:
  ao-jp:
    mapper: MBC1+RAM+BATTERY
    cartridge_type: 0x03
    rom_bytes: 0x080000
    rom_banks_16k: 32
    sram_bytes: 0x8000
    sha256: 71a70e5f77c109177d21c998310ffe01a68e8cd2f41e72e7129093b890c7d3d1
  blue-us-eu:
    mapper: MBC3+RAM+BATTERY
    cartridge_type: 0x13
    rom_bytes: 0x100000
    rom_banks_16k: 64
    sram_bytes: 0x8000
    sha256: 2a951313c2640e8c2cb21f25d1db019ae6245d9c7121f754fa61afd7bee6452d
  blue-fr:
    mapper: MBC5+RAM+BATTERY
    cartridge_type: 0x1B
    rom_bytes: 0x100000
    rom_banks_16k: 64
    sram_bytes: 0x8000
    sha256: 73dee67befed0c39cd0a6ed53a98ff5b98b3bddc3e7a0dae1d982776a4d0889b
  blue-de:
    mapper: MBC5+RAM+BATTERY
    cartridge_type: 0x1B
    rom_bytes: 0x100000
    rom_banks_16k: 64
    sram_bytes: 0x8000
    sha256: 2cfec2223090dc9f544aa36c99c48801be5018757a1366b88d8f40739541458e
  blue-it:
    mapper: MBC5+RAM+BATTERY
    cartridge_type: 0x1B
    rom_bytes: 0x100000
    rom_banks_16k: 64
    sram_bytes: 0x8000
    sha256: e197c7535135a516fe9bf92cf7821c9f72926bf90fce3a2a5742d1b0b6a0564b
  blue-es:
    mapper: MBC5+RAM+BATTERY
    cartridge_type: 0x1B
    rom_bytes: 0x100000
    rom_banks_16k: 64
    sram_bytes: 0x8000
    sha256: 31317f74fed2935dfc5fbb6ada766cf8515949c85c6c6e8d32d0f752b85b8f9e

expanded:
  mapper: MBC5+RAM+BATTERY
  cartridge_type: 0x1B
  rom_size_code: 0x08
  rom_bytes: 0x800000
  rom_banks_16k: 512
  ram_size_code: 0x04
  sram_bytes: 0x20000
  sram_banks_8k: 16
  preserve_sgb_flag: true

ranges:
  ao-jp:
    legacy_rom_banks: 0x000-0x01F
    expansion_rom_banks: 0x020-0x1FF
  international:
    legacy_rom_banks: 0x000-0x03F
    expansion_rom_banks: 0x040-0x1FF
  all:
    legacy_sram_banks: 0x00-0x03
    expansion_sram_banks: 0x04-0x0F
